In [23]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv("tested.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [32]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [33]:
df["Cabin"].unique()

array([nan, 'B45', 'E31', 'B57 B59 B63 B66', 'B36', 'A21', 'C78', 'D34',
       'D19', 'A9', 'D15', 'C31', 'C23 C25 C27', 'F G63', 'B61', 'C53',
       'D43', 'C130', 'C132', 'C101', 'C55 C57', 'B71', 'C46', 'C116',
       'F', 'A29', 'G6', 'C6', 'C28', 'C51', 'E46', 'C54', 'C97', 'D22',
       'B10', 'F4', 'E45', 'E52', 'D30', 'B58 B60', 'E34', 'C62 C64',
       'A11', 'B11', 'C80', 'F33', 'C85', 'D37', 'C86', 'D21', 'C89',
       'F E46', 'A34', 'D', 'B26', 'C22 C26', 'B69', 'C32', 'B78',
       'F E57', 'F2', 'A18', 'C106', 'B51 B53 B55', 'D10 D12', 'E60',
       'E50', 'E39 E41', 'B52 B54 B56', 'C39', 'B24', 'D28', 'B41', 'C7',
       'D40', 'D38', 'C105'], dtype=object)

In [34]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [37]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [38]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [39]:
df["Fare"] = df["Fare"].fillna(df["Fare"].mean())

In [46]:
df.drop("Cabin", axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,C

In [59]:
vizh = df[df["Survived"] == 1]
vizh["Sex"].unique()
vizh.shape[0]/df.shape[0]

0.36363636363636365

In [56]:
men = df[df["Sex"] == "male"]
men['Age'].mean()

np.float64(30.272699293414263)

In [57]:
women = df[df["Sex"] == "female"]
women['Age'].mean()

np.float64(30.27239973050095)

In [61]:
vizh["Age"].mean()

np.float64(30.27239973050095)

In [62]:
pogib = df[df["Survived"] == 0]
pogib['Age'].mean()

np.float64(30.272699293414263)

In [66]:
df_first = df[(df["Age"] > 30) & (df['Sex'] == 'male') & (df['Pclass'] == 1)]
df_first

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
11,903,0,1,"Jones, Mr. Charles Cresson",male,46.00000,0,0,694,26.0000,NaN,S
20,912,0,1,"Rothschild, Mr. Martin",male,55.00000,1,0,PC 17603,59.4000,NaN,C
28,920,0,1,"Brady, Mr. John Bertram",male,41.00000,0,0,113054,30.5000,A21,S
41,933,0,1,"Franklin, Mr. Thomas Parham",male,30.27259,0,0,113778,26.5500,D34,S
46,938,0,1,"Chevre, Mr. Paul Romaine",male,45.00000,0,0,PC 17594,29.7000,A9,C
67,959,0,1,"Moore, Mr. Clarence Bloomfield",male,47.00000,0,0,113796,42.4000,NaN,S
68,960,0,1,"Tucker, Mr. Gilbert Milligan Jr",male,31.00000,0,0,2543,28.5375,C53,C
75,967,0,1,"Keeping, Mr. Edwin",male,32.50000,0,0,113503,211.5000,C132,C
81,973,0,1,"Straus, Mr. Isidor",male,67.00000,1,0,PC 17483,221.7792,C55 C57,S
82,974,0,1,"Case, Mr. Howard Brown",male,49.00000,0,0,19924,26.0000,NaN,S
118,1010,0,1,"Beattie, Mr. Thomson",male,36.00000,0,0,13050,75.2417,C6,C
131,1023,0,1,"Gracie, Col. Archibald IV",male,53.00000,0,0,113780,28.5000,C51,C
142,1034,0,1,"Ryerson, Mr. Arthur Larned",male,61.00000,1,3,PC 17608,262.3750,B57 B59 B63 B66,C
144,1036,0,1,"Lindeberg-Lind, Mr. Erik Gustaf (Mr Edward Lin...",male,42.00000,0,0,17475,26.5500,NaN,S
146,1038,0,1,"Hilliard, Mr. Herbert Henry",male,30.27259,0,0,17463,51.8625,E46,S
148,1040,0,1,"Crafton, Mr. John Bertram",male,30.27259,0,0,113791,26.5500,NaN,S
158,1050,0,1,"Borebank, Mr. John James",male,42.00000,0,0,110489,26.5500,D22,S
166,1058,0,1,"Brandeis, Mr. Emil",male,48.00000,0,0,PC 17591,50.4958,B10,C
177,1069,0,1,"Stengel, Mr. Charles Emil Henry",male,54.00000,1,0,11778,55.4417,C116,C
181,1073,0,1,"Compton, Mr. Alexander Taylor Jr",male,37.00000,1,1,PC 17756,83.1583,E52,C
191,1083,0,1,"Salomon, Mr. Abraham L",male,30.27259,0,0,111163,26.0000,NaN,S
202,1094,0,1,"Astor, Col. John Jacob",male,47.00000,1,0,PC 17757,227.5250,C62 C64,C
205,1097,0,1,"Omont, Mr. Alfred Fernand",male,30.27259,0,0,F.C. 12998,25.7417,NaN,C
215,1107,0,1,"Head, Mr. Christopher",male,42.00000,0,0,113038,42.5000,B11,S
217,1109,0,1,"Wick, Mr. George Dennick",male,57.00000,1,1,36928,164.8667,NaN,S
234,1126,0,1,"Cumings, Mr. John Bradley",male,39.00000,1,0,PC 17599,71.2833,C85,C
236,1128,0,1,"Warren, Mr. Frank Manley",male,64.00000,1,0,110813,75.2500,D37,C
242,1134,0,1,"Spedden, Mr. Frederic Oakley",male,45.00000,1,1,16966,134.5000,E34,C
245,1137,0,1,"Kenyon, Mr. Frederick R",male,41.00000,1,0,17464,51.8625,D21,S
266,1158,0,1,"Chisholm, Mr. Roderick Robert Crispin",male,30.27259,0,0,112051,0.0000,NaN,S
270,1162,0,1,"McCaffry, Mr. Thomas Francis",male,46.00000,0,0,13050,75.2417,C6,C
290,1182,0,1,"Rheims, Mr. George Alexander Lucien",male,30.27259,0,0,PC 17607,39.6000,NaN,S
293,1185,0,1,"Dodge, Dr. Washington",male,53.00000,1,1,33638,81.8583,A34,S
308,1200,0,1,"Hays, Mr. Charles Melville",male,55.00000,1,1,12749,93.5000,B69,S
316,1208,0,1,"Spencer, Mr. William Augustus",male,57.00000,1,0,PC 17569,146.5208,B78,C
323,1215,0,1,"Rowe, Mr. Alfred G",male,33.00000,0,0,113790,26.5500,NaN,S
327,1219,0,1,"Rosenshine, Mr. George (Mr George Thorne"")""",male,46.00000,0,0,PC 17585,79.2000,NaN,C
331,1223,0,1,"Dulles, Mr. William Crothers",male,39.00000,0,0,PC 17580,29.7000,A18,C
355,1247,0,1,"Julian, Mr. Henry Forbes",male,50.00000,0,0,113044,26.0000,E60,S
372,1264,0,1,"Ismay, Mr. Joseph Bruce",male,49.00000,0,0,112058,0.0000,B52 B54 B56,S
378,1270,0,1,"Hipkins, Mr. William Edward",male,55.00000,0,0,680,50.0000,C39,S
404,1296,0,1,"Frauenthal, Mr. Isaac Gerald",male,43.00000,1,0,17765,27.7208,D40,C
407,1299,0,1,"Widener, Mr. George Dunton",male,50.00000,1,1,113503,211.5000,C80,C

In [67]:
df_second = df[((df['Age'] < 18) | (df['Sex'] == 'female')) & (df['Survived'] == 1)]
df_second

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.00000,0,0,330972,7.6292,NaN,Q
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.00000,0,0,2657,7.2292,NaN,C
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.00000,1,0,21228,82.2667,B45,S
...,...,...,...,...,...,...,...,...,...,...,...,...
409,1301,1,3,"Peacock, Miss. Treasteall",female,3.00000,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
410,1302,1,3,"Naughton, Miss. Hannah",female,30.27259,0,0,365237,7.7500,NaN,Q
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.00000,1,0,19928,90.0000,C78,Q
412,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.00000,0,0,347086,7.7750,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C

In [73]:
new = df.groupby(["Pclass", 'Sex']).agg({'Age':'mean', 'Fare':'mean', "Survived":"mean"}).reset_index()
new

   Pclass     Sex        Age        Fare  Survived
0       1  female  40.890904  115.591168       1.0
1       1    male  39.261546   75.586551       0.0
2       2  female  24.573086   26.438750       1.0
3       2    male  30.898260   20.184654       0.0
4       3  female  25.273153   13.735129       1.0
5       3    male  26.493421   11.989370       0.0

In [75]:
new.to_csv("new.csv", index=False)